### ISSUE TITLE
Do not expose secrets via command line arguments

### ISSUE THREAD

**Issue by Flowdalic** [open-pdf-sign/open-pdf-sign#14]
(CLI) applications that take a secret as command line argument easily leak the secret as the process table, which includes the secret argument, is viewable by every user.

Instead applications should consume secrets from file or from stdin. Hence I suggest removing the `--passphrase` option and replace it with a `--passpharse-file` and/or `--passphrase-stdin` option.

See also
- https://clig.dev/#arguments-and-flags "Do not read secrets directly from flags."
- https://www.netmeister.org/blog/passing-passwords.html

**Comment by cproof** [comment]
Thank you for the issue! We'll look into supporting stdin for keystore passphrase input in future versions.

**Comment by Flowdalic** [comment]
Please also consider the option to read the passphrase from a file, as this typically better composes.

**Comment by arashnikoo** [comment]
The easiest solution is to read the passphrase from an environment variable like $KEY_PASS.

**Comment by cproof** [comment]
In theory it should already be possible to pass it via file using the `--config` parameter and passing a yaml file looking like 

```yaml
passphrase: YOUR_PASSPHRASE
```

But I think there still is undefined behaviour when combining both config file and command line arguments that needs to be resolved. This and stdin input support is something that I'd look into in the coming days.

**Comment by Flowdalic** [comment]
> The easiest solution is to read the passphrase from an environment variable like $KEY_PASS.

While secrets in environment variables enjoy a better protection than secrets in command line arguments, there are still some drawbacks doing so. See the section"Passwords via the environment" from https://www.netmeister.org/blog/passing-passwords.html

**Comment by cproof** [comment]
Thank you all for the input!

I've adjusted the invocation as follows:
1. You can now combine a configuration yaml and command line arguments. So it's possible to fully supply both passphrase and path to a key (or parts) [in a file](https://github.com/open-pdf-sign/open-pdf-sign/blob/dev/src/test/resources/test-config-passphrase.yml) that can be submitted via parameter `--config /path/to/config.yaml`. In case of conflict, CLI arguments overrule the config file parameters.
2. In case a passphrase-protected private key is being loaded (`PKCS8EncryptedPrivateKey`) the user will be prompted for the passphrase on stdin, not being forced to supply via argument.

The changes are currently on the `dev` branch, to be merged soon.

**Comment by cproof** [comment]
This change was already included in v0.1.1 and is still part of the latest release
