### ISSUE TITLE
Removing fields, changing fonts?

### ISSUE THREAD

**Issue by bbbhltz** [open-pdf-sign/open-pdf-sign#15]
I may have missed something while reading the instructions, but is there a way to remove the Hint altogether or specify a different font?

**Comment by cproof** [comment]
Hi @bbbhltz ,
thanks for the feedback!
Removing the hint should be quite easy to implement, I'll look into that in the coming days.
On Fonts: Fonts in the signatures are limited to a specific set of fonts, specified in [PostScript Type 1 Fonts supported by PDFBox](https://pdfbox.apache.org/docs/2.0.1/javadocs/org/apache/pdfbox/pdmodel/font/PDType1Font.html). So in theory we could only support the fonts listed there.

**Comment by bbbhltz** [comment]
Ah, excellent. I thought I misread something in the docs.

**Comment by cproof** [comment]
This was implemented in [7191fb9](https://github.com/open-pdf-sign/open-pdf-sign/commit/7191fb92949afc2764acaf48ec969533ddca9851) and is part of the `v0.1.3` release. By passing the newly introduced `--no-hint`-parameter it is now possible to remove the hint row.
