### ISSUE TITLE
Long-Term Validation support

### ISSUE THREAD

**Issue by mpiot** [open-pdf-sign/open-pdf-sign#30]
When using the tool to certify a PDF, the CRL (Certificate Revokation List) is not added to the document. Because of that, Adobe Reader for example need to query the CRL server (from the .crt file) and download it to check the certificate is not revoked.

When Adobe Reader need to do that, it marks the document as no "LTV enabled".

Is it possible using the CLI, to automatically get the CRL from the key or add it manually via the CLI ?

Refs:
- https://www.pdfa.org/long-term-validation-of-signatures/

**Comment by cproof** [comment]
I'm currently looking into that. Please find attached two documents that are [PAdES-LT and PAdES-LTA](https://ec.europa.eu/digital-building-blocks/wikis/display/ESIGKB/What+are+the+B-T-LT+and+LTA+levels+of+an+electronic+signature) enabled (using LetsEncrypt/DigiCert), from a working prototype. Would these meet your requirements?

[pades-LTA.pdf](https://github.com/open-pdf-sign/open-pdf-sign/files/10685080/pades-LTA.pdf)
[pades-LT.pdf](https://github.com/open-pdf-sign/open-pdf-sign/files/10685079/pades-LT.pdf)

It will still take a bit of time to publish, but expect this in the near-term future.

![grafik](https://user-images.githubusercontent.com/4948782/217520972-273f3759-cff4-45bb-b9c2-0f802154cb1e.png)

**Comment by mpiot** [comment]
@cproof oh yes, exactly that :)
Tested on https://ec.europa.eu/digital-building-blocks/DSS/webapp-demo/validation and seems to be that I expect. I check it on Windows later (open in Adobe Reader) but your capture show the same :)

**Comment by cproof** [comment]
Hi @mpiot ,
PAdES-LT and PAdES-LTA are now available in the latest release. If you enable on of these profiles (PAdES-LT being sufficient in practice, in my experience), supply a timestamp server and use a signature with revocation data, Adobe Reader should mark the signatures as "LTV enabled"

**Comment by mpiot** [comment]
@cproof Thanks a lot :)
