### ISSUE TITLE
Why some signature will be rotated?

### ISSUE THREAD

**Issue by CyrusHeo** [open-pdf-sign/open-pdf-sign#34]
Hello , I'm confused on some signature will be rotated. Whether it is related to PDF properties？

**Comment by cproof** [comment]
Hi, can you please give an example document and steps to reproduce?
Page rotation is handled a bit strange in PDF, but open-pdf-sign should be able to cope with that.

**Comment by CyrusHeo** [comment]
Hi, I think my problem has been solved.
Sign on a rotated PDF must rotated the PDRectangle in the same time. 
This issue is closed. Thanks.
