### ISSUE TITLE
Using -tsa option generates a second signature

### ISSUE THREAD

**Issue by luigixx73** [open-pdf-sign/open-pdf-sign#48]
When using -tsa for Time Stamp Authority validation a second signature is generated in the document.
The desired result is to generate one single signature with timestamp included from TSA in the same signature not in another one.

**Comment by cproof** [comment]
Hi @luigixx73 ,
can you please attach a sample PDF with the wrong output?
The `--timestamp` option should sign the PDf with the `baseline_t` profile, which uses the timestamp in the signature.

**Comment by luigixx73** [comment]
I'm using   "--baseline-lta" maybe it is the reason.
Thanks for you fast reply and for your nice component!

**Comment by cproof** [comment]
Ah, that makes sense. This is the expected behaviour for `baseline_lta`.
