### ISSUE TITLE
Support ECC key

### ISSUE THREAD

**Issue by NgoHuy** [open-pdf-sign/open-pdf-sign#50]
ECC is almost rolling out quickly. The project only parse pem file which doesnot cover the ECC  private key.

**Comment by cproof** [comment]
Can you please provide steps to reproduce, and how to generate an ECC key for testing?

**Comment by cproof** [comment]
Can you please try with the latest version from the `dev` branch? [open-pdf-sign.jar](https://github.com/open-pdf-sign/open-pdf-sign/suites/13676861612/artifacts/755732692)
I've added a test case, and signing works locally on my machine [ecc key](https://github.com/open-pdf-sign/open-pdf-sign/blob/dev/src/test/resources/key-ecc.pem)

**Comment by NgoHuy** [comment]
I have found that my private key begin with `-----BEGIN EC PARAMETERS----- ` then removed those line worked this dev branch. 
Thank you very much.

**Comment by NgoHuy** [comment]
Additional should we use pfx as full combine instead?

**Comment by cproof** [comment]
Thanks for the feedback!

You can use pfx is you prefer, as it might speed up the signature process slightly. In this case, just use the `--key` and `--passphrase` parameters without specifying a `--certificate`. If you don't, the conversion from PEM/CRT to an in-memory pfx is done on-the-fly.
