### ISSUE TITLE
PDF is locked after signing, Adobe Acrobat users cannot add more signatures

### ISSUE THREAD

**Issue by grupster** [open-pdf-sign/open-pdf-sign#53]
Some users report that they cannot add more signatures to a signed PDF. It happens with Adobe Acrobat PRO DC only.

**Comment by cproof** [comment]
Thank you for the issue! This is probably a side-effect of certifying the document, and Adobe users trying to counter-sign instead of counter-certify. I'll look into that!

**Comment by cproof** [comment]
Please check again with v0.1.6 and setting `certification` to `not-certified`.
