### ISSUE TITLE
Can I use this library in an ASP.NET Core project

### ISSUE THREAD

**Issue by tuanhm11299** [open-pdf-sign/open-pdf-sign#59]
Hi, Currently I am building a Website for Sign PDF Invoices or Contracts in Viet Nam. I am having some questions:

- Can I use this in Viet Nam?
- Is it possible to use the release pkg of this library in my ASP.NET Core Web API project?

Thank you.

**Comment by cproof** [comment]
Hi,
from a legal view, you need to check with local Viet Nam law, what qualifications there are for digital signature.  
You can probably use `open-pdf-sign` serverside by wrapping the CLI invocation in ASP.NET similar as it's done in our [node wrapper](https://github.com/open-pdf-sign/open-pdf-sign-node) of you have commandline access and a JRE available on your backend.

**Comment by tuanhm11299** [comment]
Thank you, @cproof. 
I will verify with my client about the qualification of signing PDF in Viet Nam. I will let you know if I have something new.
