### ISSUE TITLE
Can I use this project to sign documents with ID Austria?

### ISSUE THREAD

**Issue by davidmann4** [open-pdf-sign/open-pdf-sign#69]
Great project! Also nice that it was supported by Netidee!

 I am a little bit lost when it comes to the certificate part of the whole process. How could I sign a document using Austria ID? 
 
 Or where could I get a certificate that has some meaning in austria speaking of legal terms?

**Comment by cproof** [comment]
Thank you for your kind words, and sorry for the late reply!
The ID Austria (IDA) is using a qualified certificate that's stored centrally. Unfortunately, `open-pdf-sign` cannot be used to sign PDFs with the IDA certificate, as `open-pdf-sign` requires local certificates/keys. An overview on the IDA architecture can be found at [EGIZ](https://eid.egiz.gv.at/).
