### ISSUE TITLE
Changing how "Visible signatures" look like

### ISSUE THREAD

**Issue by onidlo** [open-pdf-sign/open-pdf-sign#72]
By default, visible signature looks like this:
![image](https://github.com/open-pdf-sign/open-pdf-sign/assets/11643311/49f3f1c1-0d95-4dcc-99f0-22a771c64c8a)

I know it is possible to hide hint and change image located on the left side. Or change labels "Signee" and "Timestamp". But I would like to change it completely, to something like really simple, for example like this:

![image](https://github.com/open-pdf-sign/open-pdf-sign/assets/11643311/b62c79a1-445d-4f7f-b735-1044a0084ec0)

I looked into the source code of open-pdf-sign, but could not find out how can this be changed... Any idea? 

I see this as a very requested topic, similar are here:
- Select subject fields to display/display only image #40 https://github.com/open-pdf-sign/open-pdf-sign/issues/40
-  Font size / size of picture #49 https://github.com/open-pdf-sign/open-pdf-sign/issues/49
-  Option to show only sign image without the extra information in the table #65 https://github.com/open-pdf-sign/open-pdf-sign/issues/65
- ...

**Comment by cproof** [comment]
A possibility would be to add an `--image-only` flag and then use the `setImageParameters()` method of [DSS](https://ec.europa.eu/digital-building-blocks/DSS/webapp-demo/doc/dss-documentation.html#PAdESVisibleSignatureAnnex) in the [`Signer` class](https://github.com/open-pdf-sign/open-pdf-sign/blob/master/src/main/java/org/openpdfsign/Signer.java#L158). For this, also the image proportions would needed to be read first.

Can you provide a PR?

**Comment by cproof** [comment]
I've added a `--image-only` parameter in the `dev` branch. Can you verify that this fits your use case?
The Jar file can be downladed from the GitHub action: 
https://github.com/open-pdf-sign/open-pdf-sign/actions/runs/8479173630/artifacts/1369274756

**Comment by cproof** [comment]
The `--image-only` parameter is part of release v0.2.0

**Comment by GetPsyched** [comment]
I don't think `--image-only` is the solution to this problem; what if I want to keep the signee and timestamp next to the image without the table format.

Visuals are subjective, what works for me won't work for others; the only solution to this is to revamp how visible signatures are made somehow.

Unrelated, can we not customise _where_ the visible signature is put? I'm not talking which page, but where in the page.
